# Generated by Django 4.2.7 on 2026-05-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_email_verified_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                help_text="Stores new email until it is verified.",
                max_length=254,
                null=True,
            ),
        ),
    ]
