# Generated by Django 4.2.7 on 2026-04-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("airport_pickup", "Airport Pickup"),
                            ("airport_drop", "Airport Drop"),
                            ("tour_package", "Tour Package"),
                            ("taxi_booking", "Taxi Booking"),
                        ],
                        max_length=20,
                        verbose_name="Trip Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Passenger Name"),
                ),
                (
                    "num_people",
                    models.PositiveIntegerField(verbose_name="Number of Passengers"),
                ),
                (
                    "from_location",
                    models.CharField(max_length=200, verbose_name="Pickup Location"),
                ),
                (
                    "to_location",
                    models.CharField(max_length=200, verbose_name="Drop Location"),
                ),
                ("date", models.DateField(verbose_name="Travel Date")),
                ("time", models.TimeField(verbose_name="Pickup Time")),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Notes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Booking Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
