# Generated by Django 4.2.7 on 2026-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="drop_address",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Drop Address (Geocoded)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="drop_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Drop Latitude"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="drop_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Drop Longitude"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_address",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Pickup Address (Geocoded)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pickup Latitude"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pickup Longitude"
            ),
        ),
    ]
