# Generated by Django 4.2.7 on 2026-04-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_drop_address_booking_drop_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="Phone Number"
            ),
            preserve_default=False,
        ),
    ]
