# Generated by Django 4.2.7 on 2026-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="admin_note",
            field=models.TextField(blank=True, null=True, verbose_name="Admin Note"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("driver_assigned", "Driver Assigned"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
    ]
