# Generated by Django 4.2.7 on 2026-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_admin_note_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("driver_assigned", "Driver Assigned"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
    ]
