# Generated by Django 4.2.7 on 2026-05-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_cancelled_at_alter_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="expected_duration_hours",
            field=models.PositiveIntegerField(
                default=4, verbose_name="Expected Duration (Hours)"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rejection_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rejection Reason"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.vehicle",
                verbose_name="Assigned Vehicle",
            ),
        ),
    ]
