# Generated by Django 4.2.7 on 2026-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_vehicle_booking_expected_duration_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("driver_assigned", "Driver Assigned"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="idx_booking_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_booking_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["date"], name="idx_booking_date"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["vehicle", "status"], name="idx_booking_vehicle_status"
            ),
        ),
    ]
