# Generated by Django 4.2.7 on 2026-05-19 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name="Public ID"
            ),
        ),
    ]
