# Generated by Django 4.2.7 on 2026-05-19 05:41

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('bookings', 'Booking')
    for row in MyModel.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=['public_id'])

class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
