# Generated by Django 4.2.7 on 2026-05-19 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_populate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Public ID",
            ),
        ),
    ]
